name: Patch Big Bash APK

on:
  workflow_dispatch:
    inputs:
      drive_link:
        description: 'Google Drive APK Download Link'
        required: true
        default: 'https://drive.google.com/file/d/1bSA7WcWnQ1H-uiJzng2cdB5-ntY-s9Xh/view?usp=drivesdk'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk zip unzip wget
          pip install gdown requests

      - name: Download APK from Google Drive
      
