name: repack-obb
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install UnityPy pillow gdown
      - run: |
          mkdir obb new
          gdown 1MGxpvepAchNFCzeqj8dFCZDAVclHJm38 -O obb/game.obb
          gdown 1gSb55LGQMwAVqqSfXhp7cZml_rzNpMn8 -O new.zip
          unzip -q new.zip -d new
      - run: python replace.py obb/game.obb new
      - uses: actions/upload-artifact@v4
        with:
          name: new-obb
          path: out
