# ==========================================
# DOWNLOAD ORIGINAL OBB
# ==========================================

- name: Download original OBB
  run: |

    mkdir -p input

    gdown \
      "1MGxpvepAchNFCzeqj8dFCZDAVclHJm38" \
      -O input/original.obb

    echo ""
    echo "OBB:"
    ls -lh input/original.obb

    test -s input/original.obb


# ==========================================
# DOWNLOAD UPDATED TEXT ZIP
# ==========================================

- name: Download updated 12-player files
  run: |

    gdown \
      "15h2jw5xh98tr6eDCUobruPTntMxAywDX" \
      -O input/updated_text_12_players.zip

    echo ""
    echo "UPDATED ZIP:"
    ls -lh input/updated_text_12_players.zip

    test -s input/updated_text_12_players.zip
